project:
  type: book

book:
  title: "Cookbook Polars for R"
  author: "Damien Dotta"
  favicon: logo_cookbook_rpolars.png
  description: A side-by-side comparison of polars, R base, dplyr, tidyr and data.table packages.
  keyword: polars, dplyr, tidyr, data.table, dataframe, performance, data science, data engineering
  url: https://ddotta.github.io/cookbook-rpolars/
  page-navigation: true
  sidebar: 
    logo: logo_cookbook_rpolars.png
    search: true
  repo-url: https://github.com/ddotta/cookbook-rpolars/
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  image: polar-bear-airpods-no-background.png

  chapters:
    - index.qmd
    - first_steps.qmd
    - data_manipulation.qmd
    - import_export.qmd
    - lazy_execution.qmd
    - duckdb.qmd

format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: custom.css
