name: Render and Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@main

      - name: Install packages
        run: |
          R -e 'install.packages("rmarkdown")'

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: book # By default, the current working dir is used i.e `quarto render .`

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: book
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      